<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Amits-MacBook-Air.local" failures="0" tests="1" name="com.test.AcceptanceIT" time="272.281" errors="1" timestamp="28 Feb 2022 20:57:25 GMT" skipped="0">
  <testcase classname="com.test.AcceptanceIT" name="parallelRun" time="272.281">
    <error message="There were failing tests. Refer to the Courgette html report for more details." type="courgette.runtime.CourgetteTestFailureException">
      <![CDATA[courgette.runtime.CourgetteTestFailureException: There were failing tests. Refer to the Courgette html report for more details.
]]>
    </error>
  </testcase> <!-- parallelRun -->
</testsuite> <!-- com.test.AcceptanceIT -->
