<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2021-07-03T22:02:44Z" name="Surefire suite" finished-at="2021-07-03T22:03:03Z" duration-ms="19538">
    <groups>
    </groups>
    <test started-at="2021-07-03T22:02:44Z" name="Surefire test" finished-at="2021-07-03T22:03:03Z" duration-ms="19538">
      <class name="com.test.AcceptanceIT">
        <test-method is-config="true" signature="initialize()[pri:0, instance:com.test.AcceptanceIT@71e9ddb4]" started-at="2021-07-03T22:02:44Z" name="initialize" finished-at="2021-07-03T22:02:44Z" duration-ms="357" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initialize -->
        <test-method signature="parallelRun()[pri:0, instance:com.test.AcceptanceIT@71e9ddb4]" started-at="2021-07-03T22:02:44Z" name="parallelRun" finished-at="2021-07-03T22:03:03Z" duration-ms="19155" status="FAIL">
          <exception class="courgette.runtime.CourgetteTestFailureException">
            <message>
              <![CDATA[There were failing tests. Refer to the Courgette html report for more details.]]>
            </message>
            <full-stacktrace>
              <![CDATA[courgette.runtime.CourgetteTestFailureException: There were failing tests. Refer to the Courgette html report for more details.
]]>
            </full-stacktrace>
          </exception> <!-- courgette.runtime.CourgetteTestFailureException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- parallelRun -->
      </class> <!-- com.test.AcceptanceIT -->
    </test> <!-- Surefire test -->
  </suite> <!-- Surefire suite -->
</testng-results>
